/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    './storage/framework/views/*.php',
    './resources/views/**/*.blade.php',
    './resources/js/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#2c3437",
        "on-primary": "#e5fff0",
        "on-tertiary-fixed-variant": "#334d76",
        "on-tertiary-container": "#2a446c",
        "on-secondary-container": "#40555f",
        "secondary-fixed-dim": "#c1d8e4",
        "surface-container-highest": "#dce4e8",
        "on-tertiary-fixed": "#133057",
        "tertiary": "#466089",
        "secondary-fixed": "#cfe6f2",
        "tertiary-fixed-dim": "#a5bfee",
        "error-container": "#fa746f",
        "inverse-primary": "#7dfcc9",
        "surface-dim": "#d4dbdf",
        "primary-fixed-dim": "#6bebb9",
        "surface-tint": "#006d4e",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-surface": "#2c3437",
        "secondary-container": "#cfe6f2",
        "surface": "#f7f9fb",
        "on-surface-variant": "#596064",
        "primary-fixed": "#7af9c7",
        "surface-container-low": "#f0f4f7",
        "on-primary-fixed-variant": "#00694b",
        "tertiary-dim": "#3a547c",
        "on-primary-fixed": "#004933",
        "error-dim": "#67040d",
        "surface-variant": "#dce4e8",
        "tertiary-container": "#b3cdfd",
        "on-tertiary": "#f8f8ff",
        "outline-variant": "#acb3b7",
        "tertiary-fixed": "#b3cdfd",
        "secondary-dim": "#415660",
        "inverse-on-surface": "#9a9d9f",
        "on-secondary-fixed-variant": "#495f69",
        "on-secondary-fixed": "#2d424c",
        "primary-dim": "#005f44",
        "secondary": "#4d626c",
        "error": "#a83836",
        "on-error-container": "#6e0a12",
        "on-primary-container": "#005e43",
        "on-error": "#fff7f6",
        "on-secondary": "#f2faff",
        "background": "#f7f9fb",
        "primary-container": "#7af9c7",
        "surface-container-high": "#e3e9ed",
        "primary": "#006d4e",
        "inverse-surface": "#0b0f10",
        "surface-container": "#eaeff2",
        "outline": "#747c80",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
    },
  },
  safelist: [
    'bg-secondary-container', 'text-on-secondary-container',
    'bg-tertiary-container', 'text-on-tertiary-container',
    'bg-surface-container-high', 'text-on-surface-variant',
    'bg-error-container', 'text-on-error-container', 'text-error',
    'bg-primary', 'bg-outline-variant',
    'text-primary', 'hover:bg-surface-bright',
    'divide-surface-container-high',
    'border-surface-container-high',
  ],
  plugins: [],
}

