/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    './storage/framework/views/*.php',
    './resources/views/**/*.blade.php',
    './resources/js/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        // primary family — valores dinámicos via CSS variables (soporte de opacidad con /xx)
        "primary":                    "rgb(var(--color-primary) / <alpha-value>)",
        "primary-dim":                "rgb(var(--color-primary-dim) / <alpha-value>)",
        "on-primary":                 "rgb(var(--color-on-primary) / <alpha-value>)",
        "primary-container":          "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary-container":       "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "primary-fixed":              "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim":          "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed":           "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant":   "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "surface-tint":               "rgb(var(--color-primary) / <alpha-value>)",
        "inverse-primary":            "rgb(var(--color-inverse-primary) / <alpha-value>)",
        // surface family + texto + bordes — CSS variables para dark mode
        "on-background":             "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface":                "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant":        "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "surface":                   "rgb(var(--color-surface) / <alpha-value>)",
        "background":                "rgb(var(--color-surface) / <alpha-value>)",
        "surface-bright":            "rgb(var(--color-surface-bright) / <alpha-value>)",
        "surface-dim":               "rgb(var(--color-surface-dim) / <alpha-value>)",
        "surface-variant":           "rgb(var(--color-surface-variant) / <alpha-value>)",
        "surface-container-lowest":  "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-container-low":     "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container":         "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-high":    "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "outline":                   "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant":           "rgb(var(--color-outline-variant) / <alpha-value>)",
        "inverse-on-surface":        "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "inverse-surface":           "#0b0f10",
        // tokens estáticos (tertiary, secondary, error)
        "on-tertiary-fixed-variant": "#334d76",
        "on-tertiary-container": "#2a446c",
        "on-secondary-container": "#40555f",
        "secondary-fixed-dim": "#c1d8e4",
        "on-tertiary-fixed": "#133057",
        "tertiary": "#466089",
        "secondary-fixed": "#cfe6f2",
        "tertiary-fixed-dim": "#a5bfee",
        "error-container": "#fa746f",
        "secondary-container": "#cfe6f2",
        "tertiary-dim": "#3a547c",
        "error-dim": "#67040d",
        "tertiary-container": "#b3cdfd",
        "on-tertiary": "#f8f8ff",
        "tertiary-fixed": "#b3cdfd",
        "secondary-dim": "#415660",
        "on-secondary-fixed-variant": "#495f69",
        "on-secondary-fixed": "#2d424c",
        "secondary": "#4d626c",
        "error": "#a83836",
        "on-error-container": "#6e0a12",
        "on-error": "#fff7f6",
        "on-secondary": "#f2faff",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
    },
  },
  safelist: [
    'bg-secondary-container', 'text-on-secondary-container',
    'bg-tertiary-container', 'text-on-tertiary-container',
    'bg-surface-container-high', 'text-on-surface-variant',
    'bg-error-container', 'text-on-error-container', 'text-error',
    'bg-primary', 'bg-outline-variant',
    'text-primary', 'hover:bg-surface-bright',
    'divide-surface-container-high',
    'border-surface-container-high',
  ],
  plugins: [],
}

